### ISSUE TITLE
no more nowplaying updates after a comeback from the history link

### ISSUE THREAD

**Issue by shangril** [musique-libre/dmz.fm#2]
File : index.html 

Bug spotted by ardoisebleue in Iceweasel

When clicking on "OGG" (direct link to the stream) then coming back to the page by using the "go back" feature of the browser, the "nowplaying" is stuck to what was displayed before going back and no longer refreshes. 

I think that it is because the page is in static HTML. The browser probably just request a timestamp to see if the file has changed and don't reload it ; but also no longer runs the REFRESHes of the "nowplaying' iframe. 

It can probably be fixed by adding a META http-equiv "pragma no cache" in the HEAD section of the HTML code.

**Comment by Afterster** [comment]
Fixed with recommended html meta tags. Thanks.
